### PR TITLE
Fix for misc memory leaks

### PR DESCRIPTION
**Pull request by IvanRF**
https://github.com/Insubstantial/insubstantial/issues/117

### CODE REVIEW

**Comment by kirill-grouchnikov** [comment]
Just merged this change separately. Have a rather awkward setup, so this is how I'll be treating the pull requests for now if you don't mind.

Also bumped the version to 5.1.01

**Comment by IvanRF** [comment]
It's ok, it's your code 😃 
The only drawback is that I don't be remembered as contributor 😢 haha

**Comment by kirill-grouchnikov** [comment]
Sorry about that.

**Comment by kirill-grouchnikov** [comment]
And you're right about proper contributions acknowledgement. I'll find a way to make it work beyond this round of pull requests.

**Comment by IvanRF** [comment]
wow, you found the way very fast, thanks!

**Pull request closed without merging**
