### PR TITLE
Fix case of transcoded SVG icons

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The build from source fails on linux with (totaling to 57 errors):

`[javac] /home/matthias/src/kirill-grouchnikov/flamingo/src/test/svg/transcoded/accessories_text_editor.java:10: error: class Accessories_text_editor is public, should be declared in a file named Accessories_text_editor.java`

This changeset just fixes the case of the files. With this applied I can build master.

### CODE REVIEW

**Comment by kirill-grouchnikov** [comment]
What am I missing? The files seem to already be the right case over at https://github.com/kirill-grouchnikov/flamingo/tree/master/src/test/svg/transcoded

**Comment by kirill-grouchnikov** [comment]
Oh, my bad. I was looking at the SVG file names.

In my local version the java classes are in correctly named files. I will update the repository tonight with all the latest bug fixes.

**Comment by matthiasblaesing** [comment]
I see a file named:

`accessories_text_editor.java`:  https://github.com/kirill-grouchnikov/flamingo/blob/master/src/test/svg/transcoded/accessories_text_editor.java

That file declares a class with the name:

**Comment by matthiasblaesing** [comment]
Shall I close this then?

**Comment by kirill-grouchnikov** [comment]
transcoded

Something's weird. The files are definitely correct case on my Windows machine. But "git diff" and "git push" operate on the existing files in the repository instead of renaming them.

**Comment by kirill-grouchnikov** [comment]
https://github.com/kirill-grouchnikov/flamingo/tree/master/src/test/svg/transcoded should be good now. After reading https://stackoverflow.com/questions/2528589/git-windows-case-sensitive-file-names-not-handled-properly I removed the entire folder and then readded it to enforce correct filename casing

**Comment by matthiasblaesing** [comment]
Thank you - after pulling the latest changeset from master I can build cleanly.

**Pull request closed without merging**
